# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=24w09a
yarn_mappings=24w09a+build.11
loader_version=0.15.7

# Mod Properties
mod_version=1.0.0-alpha.5
maven_group=mbtw.mbtw
archives_base_name=mbtw

# Dependencies
fabric_version=0.96.7+1.20.5

jmx_version=1.22

mc_tag = mc119